// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzowcknilqdikrivcaba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6b3dja25pbHFkaWtyaXZjYWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzQyNzksImV4cCI6MjA2MDU1MDI3OX0.dj3LHCTO-d4BVrWrtWu6hbVerb1K9zgHCrTuCpLEto8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);